services:
#    platypus.example:
#        class: PlatypusBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#    checkOldPassword:
#        class: PlatypusBundle\Services\CheckOldPassword
        
    validator.checkPassword:
        class: 'PlatypusBundle\Validator\Constraints\CheckPasswordValidator'
        arguments:
            - '@security.encoder_factory'
            - '@security.token_storage'
            - '@request_stack'
        tags:
            - { name: 'validator.constraint_validator', alias: 'validatorCheckPassword' }
        
    validator.checkOldPassword:
            class: 'PlatypusBundle\Validator\Constraints\CheckOldPasswordValidator'
            arguments:
                - '@security.encoder_factory'
                - '@security.token_storage'
                - '@request_stack'
            tags:
                - { name: 'validator.constraint_validator', alias: 'validatorCheckOldPassword' }
    
    validator.checkNewPassword:
            class: 'PlatypusBundle\Validator\Constraints\CheckNewPasswordValidator'
            arguments:
                - '@security.token_storage'
                - '@request_stack'
            tags:
                - { name: 'validator.constraint_validator', alias: 'validatorCheckNewPassword' }
                
    doctrineListener.notification:
        class: 'PlatypusBundle\DoctrineListener\PasswordEncrypter'
        arguments: ['@security.encoder_factory']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            
#    doctrineListener.userelete:
#            class: 'PlatypusBundle\DoctrineListener\UserOnDelete'
#            arguments: ['@doctrine.orm.entity_manager']
#            tags:
#                - { name: doctrine.event_listener, event: onDelete }


